#ifndef utils_h
#define utils_h

int get_int(int *number, int min, int max);
int get_long(long *number, long min, long max);
int get_double (double *number, double min, double max);
int get_char (char *number, int min, int max);

#define get_everything(X, Y, Z) _Generic((X), \
    int*: get_int, \
    long*: get_long, \
    double*: get_double, \
    char*: get_char \
)(X, Y, Z)

void generate_products (Ozon **product, int* products_number);

static char *product_names[] = {
    "UltraClean Detergent",
    "SmartHome Hub",
    "EcoFresh Air Purifier",
    "PowerBoost Charger",
    "CozyDream Blanket",
    "AquaPure Water Bottle",
    "FitTrack Smartwatch",
    "SafeShield Helmet",
    "BrightGlow Lamp",
    "ChillMate Cooler",
    "ZenBreeze Diffuser",
    "QuickBake Oven",
    "GlowSkin Cream",
    "MegaBass Headphones",
    "SwiftGrip Gloves",
    "PureTone Earbuds",
    "ActiveStep Shoes",
    "CloudSoft Pillow",
    "StormForce Umbrella",
    "RapidMix Blender",
    "FreshVibes Candle",
    "GourmetChef Knife",
    "ToughTrail Backpack",
    "LuxeTouch Wallet",
    "TravelMate Suitcase",
    "TrueFocus Camera",
    "HydroGuard Flask",
    "SpeedySlice Cutter",
    "SmartClean Mop",
    "BoldBrew Coffee Maker",
    "SmoothFlow Pen",
    "EasyChop Board",
    "BrightPath Flashlight",
    "MaxiCharge Power Bank",
    "LuxeStyle Watch",
    "PureGrip Tennis Racket",
    "VitalCore Supplement",
    "HeatWave Kettle",
    "DreamChic Organizer",
    "AquaEase Filter",
    "GlidePro Skateboard",
    "SolarSmart Panel",
    "StoneEdge Knife Set",
    "QuickSew Machine",
    "ProHeat Iron",
    "HomeGuard Security Camera",
    "RapidWash Washer",
    "AromaBliss Tea Set",
    "SparkClean Toothbrush",
    "GlowTime Alarm Clock",
    "SwiftCharge Adapter",
    "ChillEase Fan",
    "ZenTime Yoga Mat",
    "UltraLight Tent",
    "FreshPack Lunch Box",
    "TurboGrill BBQ Set",
    "CloudWear Hoodie",
    "EcoBreeze Fan",
    "DreamFit Socks",
    "StoneCraft Mug",
    "EasyFix Toolkit",
    "AquaStep Flip-Flops",
    "GlideEase Roller Skates",
    "MegaClean Vacuum",
    "ShineBright Mirror",
    "SwiftLift Dumbbells",
    "LuxeBrew Espresso Machine",
    "SmoothCare Shampoo",
    "BoldStep Boots",
    "TrueTone Speakers",
    "LightWave Projector",
    "ChillCloud Mattress",
    "PureComfort Chair",
    "PowerMax Extension Cord",
    "ZenGlow Night Light",
    "HydroBoost Showerhead",
    "QuickClean Scrubber",
    "GlowFresh Toothpaste",
    "AromaFlow Oil Diffuser",
    "BrightFlex Desk Lamp",
    "EcoChic Tote Bag",
    "QuickFix Adhesive",
    "GourmetGrill Pan",
    "VitalMix Blender Bottle",
    "SpeedGrip Mouse",
    "StoneBrew Teapot",
    "AquaShield Raincoat",
    "TurboWash Soap",
    "SmartFit Band",
    "CloudEase Throw",
    "LuxeSkin Serum",
    "PowerCore Battery",
    "PureChill Ice Maker",
    "GlideClean Squeegee",
    "UltraTone Microphone",
    "FreshGuard Mask",
    "StormWear Jacket",
    "ZenEase Hammock",
    "ChillWave Cooler Bag",
    "GlowTime Clock",
    "Bober"
};

#endif
